/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unit.converter;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author Korisnik
 */
public class ConverterForm extends javax.swing.JFrame {

    private final ArrayList<UnitGroup> unitGroups;
    
    /**
     * Creates new form ConverterForm
     */
    public ConverterForm() {
        initComponents();
        setLocationRelativeTo(null);
        
        unitGroups = new ArrayList<>();
        
        UnitGroup length = new UnitGroup("Length", "mm", 
                new String[] { "cm", "dm", "m", "km", "inch", "foot", "yard", "mile" }, 
                new double[] { 10, 100, 1000, 10000, 25.4, 304.8, 914.4, 1609000 });
        
        unitGroups.add(length);
        
        UnitGroup volume = new UnitGroup("Volume", "mm^3", 
                new String[] { "cm^3", "dm^3", "m^3", "ml", "dl", "l", "gallon" }, 
                new double[] { 1000, 1000000, 1000000000, 1000, 100000, 1000000, 4546090 });
        
        unitGroups.add(volume);
        
        UnitGroup pressure = new UnitGroup("Pressure", "atmosphere", 
                new String[] { "Bar", "Pa", "Torr" }, 
                new double[] { 0.986923, 9.8692e-6, 0.00131579 });
        
        unitGroups.add(pressure);
        
        unitGroups.add(getCurrencyUnitGroup());
        
        for (UnitGroup unitGroup : unitGroups)
            unitComboBox.addItem(unitGroup.getName());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unitComboBox = new javax.swing.JComboBox<>();
        fromlabel = new javax.swing.JLabel();
        fromComboBox = new javax.swing.JComboBox<>();
        toComboBox = new javax.swing.JComboBox<>();
        toLabel = new javax.swing.JLabel();
        valueTextField = new javax.swing.JTextField();
        resultLabel = new javax.swing.JLabel();
        convertButton = new javax.swing.JButton();
        valueStaticLabel = new javax.swing.JLabel();
        resultStaticLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        unitComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitComboBoxActionPerformed(evt);
            }
        });

        fromlabel.setText("From");

        toLabel.setText("To");

        convertButton.setText("Convert");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        valueStaticLabel.setText("Value");

        resultStaticLabel.setText("Result");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(convertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unitComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(valueTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(fromlabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(valueStaticLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultStaticLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(toLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(toComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(resultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(unitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromlabel)
                    .addComponent(fromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toLabel))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueStaticLabel)
                    .addComponent(resultStaticLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(convertButton)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private UnitGroup getCurrencyUnitGroup()
    {
        String[] units = null;
        double[] coeficients = null;
        
        try {
            URL url = new URL("http://api.fixer.io/latest");
            
            InputStream istream = url.openStream();
            
            BufferedReader reader = new BufferedReader(new InputStreamReader(istream));
            
            String response = "";
            
            int c;
            
            while((c = reader.read()) != -1) {
                response += (char)c;
            }
            
            JSONObject object = new JSONObject(response);
            
            JSONObject rates = object.getJSONObject("rates");
            
            units = new String[] { "GBP", "USD", "THB", "HUF", "CNY" };
            coeficients = new double[] { 
                rates.getDouble("GBP"), 
                rates.getDouble("USD"),
                rates.getDouble("THB"),
                rates.getDouble("HUF"),
                rates.getDouble("CNY")
            };
            
        } catch (MalformedURLException ex) {
            Logger.getLogger(ConverterForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ConverterForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return new UnitGroup("Currency", "EUR", units, coeficients);
    }
    
    private UnitGroup getSelectedUnitGroup()
    {
        int selectedIndex = unitComboBox.getSelectedIndex();
        return unitGroups.get(selectedIndex);
    }
    
    private void unitComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitComboBoxActionPerformed
        UnitGroup selectedGroup = getSelectedUnitGroup();
        
        fromComboBox.removeAllItems();
        toComboBox.removeAllItems();
        
        for (String unit : selectedGroup.getUnits()) {
            fromComboBox.addItem(unit);
            toComboBox.addItem(unit);
        }
    }//GEN-LAST:event_unitComboBoxActionPerformed

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        UnitGroup selectedGroup = getSelectedUnitGroup();
        
        String text = valueTextField.getText();
        double number = 0;
        
        try {
            number = Double.parseDouble(text);
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Pogrešno unijeta vreijednost");
        }
        
        double converted = selectedGroup.convert(number, fromComboBox.getSelectedIndex(), toComboBox.getSelectedIndex());
        resultLabel.setText("" + converted);
    }//GEN-LAST:event_convertButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConverterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConverterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConverterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConverterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConverterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convertButton;
    private javax.swing.JComboBox<String> fromComboBox;
    private javax.swing.JLabel fromlabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel resultStaticLabel;
    private javax.swing.JComboBox<String> toComboBox;
    private javax.swing.JLabel toLabel;
    private javax.swing.JComboBox<String> unitComboBox;
    private javax.swing.JLabel valueStaticLabel;
    private javax.swing.JTextField valueTextField;
    // End of variables declaration//GEN-END:variables
}
